networks:
  p2p:
    driver: bridge

services:
  rate-limiter-bootstrap:
    build:
      context: . 
      dockerfile: ./demo/Dockerfile
    networks:
      - p2p
    environment:
      - CACHE_DIRECTORY=./data
    volumes:
      - ./demo/data:/data

  rate-limiter:
    build: .
    networks:
      - p2p
    environment:
      - BOOTSTRAP_PEER=/ip4/172.18.0.2/tcp/40343/p2p/12D3KooWR1yxKWRyVGuNjdnZQegQid8vVm96d2CJhsj8QR4KbReA
      - CACHE_DIRECTORY=./data
      - METRICS_ENABLED=true
    deploy:
      replicas: 3
    volumes:
      - ./demo/data:/data

  nginx:
    image: nginx:latest
    networks:
      - p2p
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro