networks:
  p2p:
    driver: bridge

services:
  rate-limiter-bootstrap:
    build: .
    networks:
      - p2p
    environment:
      - CACHE_DIRECTORY=./data
    volumes:
      - ./data:/data

  rate-limiter:
    build: .
    networks:
      - p2p
    environment:
      - BOOTSTRAP_PEER=/ip4/172.18.0.2/tcp/39721/p2p/12D3KooWBXQWYrxR77ehLnd3Lzoie83EhtVJ1cqk17vLW4vsdfq7
      - CACHE_DIRECTORY=./data
      - METRICS_ENABLED=true
    deploy:
      replicas: 3
    volumes:
      - ./data:/data

  nginx:
    image: nginx:latest
    networks:
      - p2p
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro